"""
Roblox Copy Helper — safe local companion for SteamGuard Loader.

This tool intentionally avoids reading browser/Studio cookies, accepting Roblox
security cookies, or sending secrets to third-party services. It runs a localhost
HTTP bridge that can receive animation IDs from the included Studio Lua snippet,
write a local export report, and return a deterministic ID mapping that Roblox
Studio can apply during authorized workflows.

Build a standalone Windows exe with build_roblox_copy_tool.bat.
"""
from __future__ import annotations

import argparse
import json
import os
import signal
import sys
import threading
import time
import webbrowser
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Dict, Tuple

APP_NAME = "Rivvak Roblox Copy Helper"
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 6969
ROOT = Path(__file__).resolve().parent
EXPORT_DIR = Path(os.environ.get("APPDATA", str(Path.home()))) / "SteamGuard" / "roblox_copy_exports"
LUA_SCRIPT = ROOT / "LuaScript.lua"
README = ROOT / "README.md"

_state_lock = threading.Lock()
_state = {
    "ready": False,
    "last_mapping": {},
    "last_export": "",
    "last_count": 0,
    "started_at": datetime.now(timezone.utc).isoformat(),
}


def _utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")


def _normalize_ids(payload: dict) -> Dict[str, str]:
    raw = payload.get("ids") or {}
    if isinstance(raw, list):
        return {str(i): str(v) for i, v in enumerate(raw) if str(v).strip()}
    if isinstance(raw, dict):
        cleaned = {}
        for name, value in raw.items():
            text = str(value).strip()
            if text:
                cleaned[str(name)] = text
        return cleaned
    return {}


def _make_mapping(ids: Dict[str, str], passthrough: bool) -> Dict[str, str]:
    # Passthrough mode is deliberate: the helper is a local bridge/export tool,
    # not a credential collector or unauthorized re-uploader.
    if passthrough:
        return {old_id: old_id for old_id in ids.values()}
    return {old_id: old_id for old_id in ids.values()}


def _write_export(ids: Dict[str, str], mapping: Dict[str, str], source: str) -> Path:
    EXPORT_DIR.mkdir(parents=True, exist_ok=True)
    path = EXPORT_DIR / f"roblox_copy_export_{_utc_stamp()}.json"
    doc = {
        "tool": APP_NAME,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "source": source,
        "count": len(ids),
        "ids_by_name": ids,
        "mapping": mapping,
        "notes": (
            "Safe local export generated by Rivvak Roblox Copy Helper. "
            "No Roblox cookies are read, stored, accepted, or transmitted."
        ),
    }
    path.write_text(json.dumps(doc, indent=2), encoding="utf-8")
    return path


class CopyHandler(BaseHTTPRequestHandler):
    server_version = "RivvakRobloxCopyHelper/1.0"

    def _send_json(self, status: int, data) -> None:
        body = json.dumps(data, indent=2).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "http://127.0.0.1")
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, fmt: str, *args) -> None:
        print(f"[{datetime.now().strftime('%H:%M:%S')}] {self.address_string()} - {fmt % args}")

    def do_OPTIONS(self) -> None:  # noqa: N802 - stdlib handler API
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "http://127.0.0.1")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self) -> None:  # noqa: N802
        with _state_lock:
            snapshot = dict(_state)
        if self.path in ("/", "/mapping"):
            self._send_json(200, snapshot["last_mapping"] if snapshot["ready"] else None)
            return
        if self.path == "/status":
            self._send_json(200, snapshot)
            return
        if self.path == "/lua":
            text = LUA_SCRIPT.read_text(encoding="utf-8") if LUA_SCRIPT.exists() else ""
            body = text.encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "text/plain; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        self._send_json(404, {"error": "Not found"})

    def do_POST(self) -> None:  # noqa: N802
        if self.path != "/":
            self._send_json(404, {"error": "Not found"})
            return
        length = int(self.headers.get("Content-Length", "0") or "0")
        raw = self.rfile.read(length)
        try:
            payload = json.loads(raw.decode("utf-8")) if raw else {}
        except json.JSONDecodeError:
            self._send_json(400, {"error": "Invalid JSON"})
            return

        ids = _normalize_ids(payload)
        mapping = _make_mapping(ids, passthrough=True)
        export = _write_export(ids, mapping, source=str(self.client_address[0]))
        with _state_lock:
            _state.update({
                "ready": True,
                "last_mapping": mapping,
                "last_export": str(export),
                "last_count": len(ids),
            })
        print(f"Received {len(ids)} animation id(s); export saved to {export}")
        self._send_json(204, {})


def _copy_lua_to_clipboard() -> bool:
    if not LUA_SCRIPT.exists():
        return False
    text = LUA_SCRIPT.read_text(encoding="utf-8")
    try:
        import tkinter as tk
        root = tk.Tk()
        root.withdraw()
        root.clipboard_clear()
        root.clipboard_append(text)
        root.update()
        root.destroy()
        return True
    except Exception:
        return False


def _print_banner(host: str, port: int) -> None:
    EXPORT_DIR.mkdir(parents=True, exist_ok=True)
    print("=" * 72)
    print(APP_NAME)
    print("=" * 72)
    print(f"Local server : http://{host}:{port}")
    print(f"Exports      : {EXPORT_DIR}")
    print(f"Lua snippet  : {LUA_SCRIPT}")
    print("\nUsage:")
    print("  1. Open Roblox Studio for an experience you own or are allowed to edit.")
    print("  2. Run the included LuaScript.lua in Studio's command bar/plugin context.")
    print("  3. Check the export JSON written above and the /status endpoint.")
    print("\nSecurity:")
    print("  This helper does not read, request, store, or transmit .ROBLOSECURITY cookies.")
    print("=" * 72)


def serve(host: str, port: int, open_status: bool = False) -> None:
    _print_banner(host, port)
    if _copy_lua_to_clipboard():
        print("Lua snippet copied to clipboard.")
    else:
        print("Lua snippet could not be copied automatically; open LuaScript.lua manually.")
    server = ThreadingHTTPServer((host, port), CopyHandler)
    if open_status:
        webbrowser.open(f"http://{host}:{port}/status")

    stop = threading.Event()

    def shutdown(*_args):
        stop.set()
        threading.Thread(target=server.shutdown, daemon=True).start()

    try:
        signal.signal(signal.SIGINT, shutdown)
        signal.signal(signal.SIGTERM, shutdown)
    except Exception:
        pass

    print("Server is running. Press Ctrl+C to stop.")
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        while not stop.is_set():
            time.sleep(0.25)
    finally:
        server.server_close()
        print("Server stopped.")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=APP_NAME)
    parser.add_argument("--host", default=DEFAULT_HOST)
    parser.add_argument("--port", default=DEFAULT_PORT, type=int)
    parser.add_argument("--open-status", action="store_true")
    args = parser.parse_args(argv)
    serve(args.host, args.port, args.open_status)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
